services:
  catalog.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=SwN12345678
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Src/Catalog/Catalog.API/Dockerfile
    depends_on: 
      - catalog.db
